/* Baidu Inc. Copyright. */
;(function(){
if(!PluginDetect)var PluginDetect={getNum:function(a,b){if(!this.num(a))return null;var d;return(d="undefined"==typeof b?/[\d][\d\.\_,-]*/.exec(a):RegExp(b).exec(a))?d[0].replace(/[\.\_-]/g,","):null},hasMimeType:function(a){if(PluginDetect.isIE)return null;var b,d,e=a.constructor==String?[a]:a;for(d=0;d<e.length;d++)if((a=navigator.mimeTypes[e[d]])&&a.enabledPlugin)if(b=a.enabledPlugin,b.name||b.description)return a;return null},findNavPlugin:function(a,b){for(var d=a.constructor==String?a:a.join(".*"),
e=!1===b?"":"\\d",e=RegExp(d+".*"+e+"|"+e+".*"+d,"i"),g=navigator.plugins,d=0;d<g.length;d++)if(e.test(g[d].description)||e.test(g[d].name))return g[d];return null},AXO:window.ActiveXObject,getAXO:function(a,b){var d=null,e=!1;try{d=new this.AXO(a),e=!0}catch(g){}return"undefined"!=typeof b?(delete d,e):d},num:function(a){return"string"!=typeof a?!1:/\d/.test(a)},compareNums:function(a,b){var d,e,g,i=window.parseInt;if(!this.num(a)||!this.num(b))return 0;if(this.plugin&&this.plugin.compareNums)return this.plugin.compareNums(a,
b);d=a.split(",");e=b.split(",");for(g=0;g<Math.min(d.length,e.length);g++){if(i(d[g],10)>i(e[g],10))return 1;if(i(d[g],10)<i(e[g],10))return-1}return 0},formatNum:function(a){if(!this.num(a))return null;for(var b=a.replace(/\s/g,"").replace(/[\.\_]/g,",").split(",").concat(["0","0","0","0"]),a=0;4>a;a++)/^(0+)(.+)$/.test(b[a])&&(b[a]=RegExp.$2);/\d/.test(b[0])||(b[0]="0");return b[0]+","+b[1]+","+b[2]+","+b[3]},initScript:function(){var a=navigator.userAgent;this.IEver=(this.isIE=!0)&&/MSIE\s*(\d\.?\d*)/i.exec(a)?
parseFloat(RegExp.$1,10):-1;this.ActiveXEnabled=!1;if(this.isIE){var b,d="Msxml2.XMLHTTP,Msxml2.DOMDocument,Microsoft.XMLDOM,ShockwaveFlash.ShockwaveFlash,TDCCtl.TDCCtl,Shell.UIHelper,Scripting.Dictionary,wmplayer.ocx".split(",");for(b=0;b<d.length;b++)if(this.getAXO(d[b],1)){this.ActiveXEnabled=!0;break}this.head="undefined"!=typeof document.getElementsByTagName?document.getElementsByTagName("head")[0]:null}this.GeckoRV=(this.isGecko=!this.isIE&&"string"==typeof navigator.product&&/Gecko/i.test(navigator.product)&&
/Gecko\s*\/\s*\d/i.test(a)?!0:!1)?this.formatNum(/rv\s*\:\s*([\.\,\d]+)/i.test(a)?RegExp.$1:"0.9"):null;this.isSafari=!this.isIE&&/Safari\s*\/\s*\d/i.test(a)?!0:!1;this.isChrome=/Chrome\s*\/\s*\d/i.test(a)?!0:!1;this.onWindowLoaded(0)},init:function(a,b){if("string"!=typeof a)return-3;var a=a.toLowerCase().replace(/\s/g,""),d;if("undefined"==typeof this[a])return-3;this.plugin=d=this[a];if("undefined"==typeof d.installed||!0==b)d.installed=null,d.version=null,d.version0=null,d.getVersionDone=null,
d.$=this;this.garbage=!1;return this.isIE&&!this.ActiveXEnabled&&this.plugin!=this.java?-2:1},isMinVersion:function(){return-3},getVersion:function(a,b,d){var e=PluginDetect;if(0>e.init(a))return null;a=e.plugin;1!=a.getVersionDone&&(a.getVersion(b,d),null===a.getVersionDone&&(a.getVersionDone=1));e.cleanup();return a.version||a.version0},getInfo:function(a,b,d){var e={},g=PluginDetect,i;if(0>g.init(a))return e;i=g.plugin;"undefined"!=typeof i.getInfo&&(null===i.getVersionDone&&g.getVersion(a,b,d),
e=i.getInfo());return e},cleanup:function(){this.garbage&&"undefined"!=typeof window.CollectGarbage&&window.CollectGarbage()},isActiveXObject:function(a){a='<object width="1" height="1" style="display:none" '+this.plugin.getCodeBaseVersion(a)+">"+this.plugin.HTML+"</object>";this.head.firstChild?this.head.insertBefore(document.createElement("object"),this.head.firstChild):this.head.appendChild(document.createElement("object"));this.head.firstChild.outerHTML=a;try{this.head.firstChild.classid=this.plugin.classID}catch(b){}a=
!1;try{this.head.firstChild.object&&(a=!0)}catch(d){}try{a&&4>this.head.firstChild.readyState&&(this.garbage=!0)}catch(e){}this.head.removeChild(this.head.firstChild);return a},codebaseSearch:function(a){var b=this;if(!b.ActiveXEnabled)return null;if("undefined"!=typeof a)return b.isActiveXObject(a);for(var d=[0,0,0,0],e,g=b.plugin.digits,i=function(a,f){return b.isActiveXObject((0==a?f:d[0])+","+(1==a?f:d[1])+","+(2==a?f:d[2])+","+(3==a?f:d[3]))},m,f,o=!1,a=0;a<g.length;a++){m=2*g[a];for(e=d[a]=
0;20>e&&!(1==m&&0<a&&o);e++)if(1<m-d[a])f=Math.round((m+d[a])/2),i(a,f)?(d[a]=f,o=!0):m=f;else{1==m-d[a]&&m--;!o&&i(a,m)&&(o=!0);break}if(!o)return null}return d.join(",")},dummy1:0};PluginDetect.onDetectionDone=function(){return-1};
PluginDetect.onWindowLoaded=function(a){var b=PluginDetect,d=window;!0!==b.EventWinLoad&&(b.winLoaded=!1,b.EventWinLoad=!0,"undefined"!=typeof d.addEventListener?d.addEventListener("load",b.runFuncs,!1):"undefined"!=typeof d.attachEvent?d.attachEvent("onload",b.runFuncs):("function"==typeof d.onload&&(b.funcs[b.funcs.length]=d.onload),d.onload=b.runFuncs));"function"==typeof a&&(b.funcs[b.funcs.length]=a)};PluginDetect.funcs=[0];
PluginDetect.runFuncs=function(){var a=PluginDetect,b;a.winLoaded=!0;for(b=0;b<a.funcs.length;b++)"function"==typeof a.funcs[b]&&(a.funcs[b](a),a.funcs[b]=null)};
PluginDetect.quicktime={mimeType:["video/quicktime","application/x-quicktimeplayer","image/x-macpaint","image/x-quicktime"],progID:"QuickTimeCheckObject.QuickTimeCheck.1",progID0:"QuickTime.QuickTime",classID:"clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B",minIEver:7,HTML:'<param name="src" value="A14999.mov" /><param name="controller" value="false" />',getCodeBaseVersion:function(a){return'codebase="#version='+a+'"'},digits:[8,64,16,0],clipTo3digits:function(a){if(null===a||"undefined"==typeof a)return null;
var b,d=this.$;b=a.split(",");a=(0>d.compareNums(a,"7,60,0,0")&&0<=d.compareNums(a,"7,50,0,0")?b[0]+","+b[1].charAt(0)+","+b[1].charAt(1)+","+b[2]:b[0]+","+b[1]+","+b[2]+","+b[3]).split(",");return a[0]+","+a[1]+","+a[2]+",0"},getVersion:function(){var a=null,b,d=this.$;b=!0;if(d.isIE){if(d.IEver>=this.minIEver&&d.getAXO(this.progID0,1))a=d.codebaseSearch();else if((b=d.getAXO(this.progID))&&b.QuickTimeVersion)a=b.QuickTimeVersion.toString(16),a=a.charAt(0)+"."+a.charAt(1)+"."+a.charAt(2);this.installed=
a?1:d.getAXO(this.progID0,1)?0:-1}else navigator.platform&&/linux/i.test(navigator.platform)&&(b=!1),b&&(b=d.findNavPlugin(["QuickTime","(Plug-in|Plugin)"]))&&b.name&&d.hasMimeType(this.mimeType)&&(a=d.getNum(b.name)),this.installed=a?1:-1;this.version=this.clipTo3digits(d.formatNum(a))}};
PluginDetect.devalvr={mimeType:"application/x-devalvrx",progID:"DevalVRXCtrl.DevalVRXCtrl.1",classID:"clsid:5D2CF9D0-113A-476B-986F-288B54571614",getVersion:function(){var a=null,b,d=this.$;if(d.isIE){var e,g;if(e=d.getAXO(this.progID,1)){b=d.instantiate("object",["classid",this.classID],["src",""]);if(g=d.getObject(b))try{g.pluginversion&&(a="00000000"+g.pluginversion.toString(16),a=a.substr(a.length-8,8),a=parseInt(a.substr(0,2),16)+","+parseInt(a.substr(2,2),16)+","+parseInt(a.substr(4,2),16)+
","+parseInt(a.substr(6,2),16))}catch(i){}d.uninstantiate(b)}this.installed=a?1:e?0:-1}else(b=d.findNavPlugin("DevalVR"))&&b.name&&d.hasMimeType(this.mimeType)&&(a=b.description.split(" ")[3]),this.installed=a?1:-1;this.version=d.formatNum(a)}};
PluginDetect.flash={mimeType:["application/x-shockwave-flash","application/futuresplash"],progID:"ShockwaveFlash.ShockwaveFlash",classID:"clsid:D27CDB6E-AE6D-11CF-96B8-444553540000",getVersion:function(){var a=function(a){return!a?null:(a=/[\d][\d\,\.\s]*[rRdD]{0,1}[\d\,]*/.exec(a))?a[0].replace(/[rRdD\.]/g,",").replace(/\s/g,""):null},b,d=this.$,e=null,g=null,i=null;if(d.isIE){for(b=15;2<b;b--)if(g=d.getAXO(this.progID+"."+b)){i=b.toString();break}if("6"==i)try{g.AllowScriptAccess="always"}catch(m){return"6,0,21,0"}try{e=
a(g.GetVariable("$version"))}catch(f){}!e&&i&&(e=i)}else(b=d.findNavPlugin("Flash"))&&b.description&&d.hasMimeType(this.mimeType)&&(e=a(b.description));this.installed=e?1:-1;this.version=d.formatNum(e);return!0}};
PluginDetect.shockwave={mimeType:"application/x-director",progID:"SWCtl.SWCtl",classID:"clsid:166B1BCA-3F9C-11CF-8075-444553540000",getVersion:function(){var a=null,b=null,d=this.$;if(d.isIE){try{b=d.getAXO(this.progID).ShockwaveVersion("")}catch(e){}"string"==typeof b&&0<b.length?a=d.getNum(b):d.getAXO(this.progID+".8",1)?a="8":d.getAXO(this.progID+".7",1)?a="7":d.getAXO(this.progID+".1",1)&&(a="6")}else(b=d.findNavPlugin("Shockwave for Director"))&&b.description&&d.hasMimeType(this.mimeType)&&(a=
d.getNum(b.description));this.installed=a?1:-1;this.version=d.formatNum(a)}};PluginDetect.div=null;PluginDetect.pluginSize=1;PluginDetect.DOMbody=null;
PluginDetect.uninstantiate=function(a){if(a)try{a[0]&&a[0].firstChild&&a[0].removeChild(a[0].firstChild),a[0]&&this.div&&this.div.removeChild(a[0]),this.div&&0==this.div.childNodes.length&&(this.div.parentNode.removeChild(this.div),this.div=null,this.DOMbody&&this.DOMbody.parentNode&&this.DOMbody.parentNode.removeChild(this.DOMbody),this.DOMbody=null),a[0]=null}catch(b){}};
PluginDetect.getObject=function(a,b){var d=null;try{a&&a[0]&&a[0].firstChild&&(d=a[0].firstChild)}catch(e){}try{b&&d&&"undefined"!=typeof d.focus&&"undefined"!=typeof document.hasFocus&&!document.hasFocus()&&d.focus()}catch(g){}return d};PluginDetect.getContainer=function(a){var b=null;a&&a[0]&&(b=a[0]);return b};PluginDetect.hideObject=function(a){if((a=this.getObject(a))&&a.style)a.style.height="0"};
PluginDetect.instantiate=function(a,b,d,e){var g=function(a){var b=a.style;b&&(b.border="0px",b.padding="0px",b.margin="0px",b.fontSize=m.pluginSize+3+"px",b.height=m.pluginSize+3+"px",b.visibility="visible",a.tagName&&"div"==a.tagName.toLowerCase()?(b.width="100%",b.display="block"):a.tagName&&"span"==a.tagName.toLowerCase()&&(b.width=m.pluginSize+"px",b.display="inline"))},i=document,m=this,f,o=i.getElementsByTagName("body")[0]||i.body,r=i.createElement("span"),p;"undefined"==typeof e&&(e="");f=
"<"+a+' width="'+m.pluginSize+'" height="'+m.pluginSize+'" ';for(p=0;p<b.length;p+=2)f+=b[p]+'="'+b[p+1]+'" ';f+=">";for(p=0;p<d.length;p+=2)f+='<param name="'+d[p]+'" value="'+d[p+1]+'" />';f+=e+"</"+a+">";if(!m.div){m.div=i.createElement("div");if(a=i.getElementById("plugindetect"))g(a),a.appendChild(m.div);else if(o)try{o.firstChild&&"undefined"!=typeof o.insertBefore?o.insertBefore(m.div,o.firstChild):o.appendChild(m.div)}catch(q){}else try{i.write('<div id="pd33993399">o</div>'),o=i.getElementsByTagName("body")[0]||
i.body,o.appendChild(m.div),o.removeChild(i.getElementById("pd33993399"))}catch(h){try{m.DOMbody=i.createElement("body"),i.getElementsByTagName("html")[0].appendChild(m.DOMbody),m.DOMbody.appendChild(m.div)}catch(j){}}g(m.div)}if(m.div&&m.div.parentNode&&m.div.parentNode.parentNode){m.div.appendChild(r);try{r.innerHTML=f}catch(k){}g(r);return[r]}return[null]};
PluginDetect.windowsmediaplayer={mimeType:["application/x-mplayer2","application/asx"],progID:"wmplayer.ocx",classID:"clsid:6BF52A52-394A-11D3-B153-00C04F79FAA6",getVersion:function(){var a=null,b=this.$,d=null;this.installed=-1;if(b.isIE){if(d=b.getAXO(this.progID))a=d.versionInfo}else if(b.hasMimeType(this.mimeType)){if(b.findNavPlugin(["Windows","Media","(Plug-in|Plugin)"],!1)||b.findNavPlugin(["Flip4Mac","Windows","Media"],!1))this.installed=0;if(!(b.isGecko&&0>b.compareNums(b.GeckoRV,b.formatNum("1.8")))&&
b.findNavPlugin(["Windows","Media","Firefox Plugin"],!1)){var d=b.instantiate("object",["type",this.mimeType[0]],[]),e=b.getObject(d);e&&(a=e.versionInfo);b.uninstantiate(d)}}a&&(this.installed=1);this.version=b.formatNum(a)}};
PluginDetect.silverlight={mimeType:"application/x-silverlight",progID:"AgControl.AgControl",digits:[9,20,9,12,31],getVersion:function(){var a=this.$,b=null,d=null,e=!1;if(a.isIE){var d=a.getAXO(this.progID),g=[1,0,1,1,1],i,m,f=function(a){return(10>a?"0":"")+a.toString()},o=function(a,b){var m=(0==a?b:g[0])+"."+(1==a?b:g[1])+"."+(2==a?b:g[2])+f(3==a?b:g[3])+f(4==a?b:g[4])+".0";try{return d.IsVersionSupported(m)}catch(e){}return!1};if(d&&"undefined"!=typeof d.IsVersionSupported){for(i=0;i<this.digits.length;i++){m=
g[i];for(m+=0==i?0:1;m<=this.digits[i];m++)if(o(i,m))e=!0,g[i]=m;else break;if(!e)break}e&&(b=g[0]+"."+g[1]+"."+g[2]+f(g[3])+f(g[4])+".0")}}else if(i=[null,null],i=a.findNavPlugin("Silverlight Plug-in",!1),o=a.isGecko&&0>=a.compareNums(a.GeckoRV,a.formatNum("1.6")),i&&a.hasMimeType(this.mimeType)){if(b=a.formatNum(i.description))g=b.split(","),30226<=parseInt(g[2],10)&&2>parseInt(g[0],10)&&(g[0]="2"),b=g.join(",");a.isGecko&&!o&&(e=!0);if(!e&&!o&&b){i=a.instantiate("object",["type",this.mimeType],
[]);if(d=a.getObject(i))"undefined"!=typeof d.IsVersionSupported&&(e=!0),e||(d.data="data:"+this.mimeType+",","undefined"!=typeof d.IsVersionSupported&&(e=!0));a.uninstantiate(i)}}this.installed=e?1:-1;this.version=a.formatNum(b)}};
PluginDetect.vlc={mimeType:"application/x-vlc-plugin",progID:"VideoLAN.VLCPlugin",compareNums:function(a,b){var d=a.split(","),e=b.split(","),g,i,m,f,o;for(g=0;g<Math.min(d.length,e.length);g++){/([\d]+)([a-z]?)/.test(d[g]);i=parseInt(RegExp.$1,10);f=2==g&&0<RegExp.$2.length?RegExp.$2.charCodeAt(0):-1;/([\d]+)([a-z]?)/.test(e[g]);m=parseInt(RegExp.$1,10);o=2==g&&0<RegExp.$2.length?RegExp.$2.charCodeAt(0):-1;if(i!=m)return i>m?1:-1;if(2==g&&f!=o)return f>o?1:-1}return 0},getVersion:function(){var a=
this.$,b,d=null;if(a.isIE){if(b=a.getAXO(this.progID))try{d=a.getNum(b.VersionInfo,"[\\d][\\d\\.]*[a-z]*")}catch(e){}this.installed=b?1:-1}else a.hasMimeType(this.mimeType)&&(b=a.findNavPlugin(["VLC","(Plug-in|Plugin)"],!1))&&b.description&&(d=a.getNum(b.description,"[\\d][\\d\\.]*[a-z]*")),this.installed=d?1:-1;this.version=a.formatNum(d)}};PluginDetect.initScript();
function md5(a){function b(a,b){var d=(a&65535)+(b&65535);return(a>>16)+(b>>16)+(d>>16)<<16|d&65535}function d(a,d,e,g,i,q){a=b(b(d,a),b(g,q));return b(a<<i|a>>>32-i,e)}function e(a,b,e,g,i,q,h){return d(b&e|~b&g,a,b,i,q,h)}function g(a,b,e,g,i,q,h){return d(b&g|e&~g,a,b,i,q,h)}function i(a,b,e,g,i,q,h){return d(e^(b|~g),a,b,i,q,h)}return function(a){var b="",d,e;for(e=0;e<a.length;e+=1)d=a.charCodeAt(e),b+="0123456789abcdef".charAt(d>>>4&15)+"0123456789abcdef".charAt(d&15);return b}(function(a){var f=
unescape(encodeURIComponent(a)),o,a=[];a[(f.length>>2)-1]=void 0;for(o=0;o<a.length;o+=1)a[o]=0;for(o=0;o<8*f.length;o+=8)a[o>>5]|=(f.charCodeAt(o/8)&255)<<o%32;f=8*f.length;a[f>>5]|=128<<f%32;a[(f+64>>>9<<4)+14]=f;for(var r,p,q,h=1732584193,j=-271733879,k=-1732584194,l=271733878,f=0;f<a.length;f+=16)o=h,r=j,p=k,q=l,h=e(h,j,k,l,a[f],7,-680876936),l=e(l,h,j,k,a[f+1],12,-389564586),k=e(k,l,h,j,a[f+2],17,606105819),j=e(j,k,l,h,a[f+3],22,-1044525330),h=e(h,j,k,l,a[f+4],7,-176418897),l=e(l,h,j,k,a[f+5],
12,1200080426),k=e(k,l,h,j,a[f+6],17,-1473231341),j=e(j,k,l,h,a[f+7],22,-45705983),h=e(h,j,k,l,a[f+8],7,1770035416),l=e(l,h,j,k,a[f+9],12,-1958414417),k=e(k,l,h,j,a[f+10],17,-42063),j=e(j,k,l,h,a[f+11],22,-1990404162),h=e(h,j,k,l,a[f+12],7,1804603682),l=e(l,h,j,k,a[f+13],12,-40341101),k=e(k,l,h,j,a[f+14],17,-1502002290),j=e(j,k,l,h,a[f+15],22,1236535329),h=g(h,j,k,l,a[f+1],5,-165796510),l=g(l,h,j,k,a[f+6],9,-1069501632),k=g(k,l,h,j,a[f+11],14,643717713),j=g(j,k,l,h,a[f],20,-373897302),h=g(h,j,k,l,
a[f+5],5,-701558691),l=g(l,h,j,k,a[f+10],9,38016083),k=g(k,l,h,j,a[f+15],14,-660478335),j=g(j,k,l,h,a[f+4],20,-405537848),h=g(h,j,k,l,a[f+9],5,568446438),l=g(l,h,j,k,a[f+14],9,-1019803690),k=g(k,l,h,j,a[f+3],14,-187363961),j=g(j,k,l,h,a[f+8],20,1163531501),h=g(h,j,k,l,a[f+13],5,-1444681467),l=g(l,h,j,k,a[f+2],9,-51403784),k=g(k,l,h,j,a[f+7],14,1735328473),j=g(j,k,l,h,a[f+12],20,-1926607734),h=d(j^k^l,h,j,a[f+5],4,-378558),l=d(h^j^k,l,h,a[f+8],11,-2022574463),k=d(l^h^j,k,l,a[f+11],16,1839030562),j=
d(k^l^h,j,k,a[f+14],23,-35309556),h=d(j^k^l,h,j,a[f+1],4,-1530992060),l=d(h^j^k,l,h,a[f+4],11,1272893353),k=d(l^h^j,k,l,a[f+7],16,-155497632),j=d(k^l^h,j,k,a[f+10],23,-1094730640),h=d(j^k^l,h,j,a[f+13],4,681279174),l=d(h^j^k,l,h,a[f],11,-358537222),k=d(l^h^j,k,l,a[f+3],16,-722521979),j=d(k^l^h,j,k,a[f+6],23,76029189),h=d(j^k^l,h,j,a[f+9],4,-640364487),l=d(h^j^k,l,h,a[f+12],11,-421815835),k=d(l^h^j,k,l,a[f+15],16,530742520),j=d(k^l^h,j,k,a[f+2],23,-995338651),h=i(h,j,k,l,a[f],6,-198630844),l=i(l,h,
j,k,a[f+7],10,1126891415),k=i(k,l,h,j,a[f+14],15,-1416354905),j=i(j,k,l,h,a[f+5],21,-57434055),h=i(h,j,k,l,a[f+12],6,1700485571),l=i(l,h,j,k,a[f+3],10,-1894986606),k=i(k,l,h,j,a[f+10],15,-1051523),j=i(j,k,l,h,a[f+1],21,-2054922799),h=i(h,j,k,l,a[f+8],6,1873313359),l=i(l,h,j,k,a[f+15],10,-30611744),k=i(k,l,h,j,a[f+6],15,-1560198380),j=i(j,k,l,h,a[f+13],21,1309151649),h=i(h,j,k,l,a[f+4],6,-145523070),l=i(l,h,j,k,a[f+11],10,-1120210379),k=i(k,l,h,j,a[f+2],15,718787259),j=i(j,k,l,h,a[f+9],21,-343485551),
h=b(h,o),j=b(j,r),k=b(k,p),l=b(l,q);a=[h,j,k,l];o="";for(f=0;f<32*a.length;f+=8)o+=String.fromCharCode(a[f>>5]>>>f%32&255);return o}(a))}
function log(a,b){var d=window,e=new Image,g="log"+new Date,i=["_="+ +new Date],m;for(m in b)Object.prototype.hasOwnProperty.call(b,m)&&i.push(encodeURIComponent(m)+"="+encodeURIComponent(b[m]));d[g]=e;e.onload=e.onerror=e.onabort=function(){e.onload=e.onerror=e.onabort=null;try{delete d[g]}catch(a){d[g]=void 0}};a+=i.join("&");if("Microsoft Internet Explorer"===navigator.appName&&(i=navigator.userAgent.split(";")[1]))i=/MSIE ([0-9]\.[0-9])/.exec(i)[1],8>+i&&(a=a.slice(0,2048));e.src=a}
var win=window,scr=screen,nav=navigator,debug=-1!==win.location.href.indexOf("debug=true"),decode=-1!==win.location.href.indexOf("decode=true"),store={},storeArray=[],isSend=!1,font=0,each=function(a,b,d){var e=[];if(a.length){for(var g=0;g<a.length;g++)e[e.length]=b.call(d,a[g]);return e}},getCookieRaw=function(a,b){var d,e=RegExp("(^| )"+a+"=([^;]*)(;|$)").exec((b||window).document.cookie);e&&(d=e[2]);return d},setCookieRaw=function(a,b,d){var d=d||{},e=d.expires;"number"==typeof d.expires&&(e=
new Date,e.setTime(e.getTime()+d.expires));document.cookie=a+"="+b+(d.path?"; path="+d.path:"")+(e?"; expires="+e.toGMTString():"")+(d.domain?"; domain="+d.domain:"")+(d.secure?"; secure":"")};function getBrowser(){var a=5,a=navigator.userAgent;return a=/msie (\d+\.\d)/i.test(a)?1:/firefox\/(\d+\.\d)/i.test(a)?3:/(\d+\.\d)?(?:\.\d)?\s+safari\/?(\d+\.\d+)?/i.test(a)&&!/chrome/i.test(a)?4:/chrome\/(\d+\.\d)/i.test(a)?2:5}
var params=[{key:"sr",value:function(){return[scr.width,scr.height,scr.colorDepth,win.devicePixelRatio||1].join("x")}},{key:"je",value:function(){return+nav.javaEnabled()}},{key:"ce",value:function(){return+nav.cookieEnabled}},{key:"tz",value:function(){return(new Date).getTimezoneOffset()}},{key:"pl",value:function(){function a(){return each(navigator.plugins,function(a){var b=each(a,function(a){return[a.type,a.suffixes].join("~")}).join(","),a=[a.name,a.description,b].join(".");return decode?a:
md5(a)},this).join("-")}function b(){function a(){var b,d=decode?d+" ":md5("Adobe Acrobat version")+" ";if(window.ActiveXObject){for(var e=2;10>e;e++)try{if(b=eval("new ActiveXObject('PDF.PdfCtrl."+e+"');"))return d+e+".?"}catch(g){}try{if(b=new ActiveXObject("PDF.PdfCtrl.1"))return d+"4.?"}catch(i){}try{if(b=new ActiveXObject("AcroPDF.PDF.1"))return d+"7.?"}catch(h){}return""}}function b(a){var d=a.key,a=a.fun,e;try{if(window.obj=new ActiveXObject(d+".1"),obj)return e=eval("obj"+a)}catch(g){}for(var i=
2;10>i;i++)try{if(obj=eval("new ActiveXObject('"+d+"."+i+"');"))return e=eval("obj"+a)}catch(h){}return""}if(function(){if(!window.ActiveXObject)return!1;try{if(window.external&&external.msActiveXFilteringEnabled&&external.msActiveXFilteringEnabled())return!1}catch(a){}return!0}()){var g=each(["QuickTime","DevalVR","Shockwave","Flash","WindowsMediaplayer","Silverlight","VLC",{key:"AliIMX.WangWangX",fun:".GetWangWangVersion()"},{key:"QQAppIEAgentEx.AgentForAndroid",fun:".TestClient()"},{key:"Baidu.Medusa",
fun:".version"},{key:"BaiduBar.Tool",fun:".userID"},{key:"APlayer3.Player",fun:".GetVersion()"}],function(a){var d="",g;if("string"===typeof a){g=a;try{d=PluginDetect.getVersion(a)}catch(i){}}else g=a.key,d=b(a);return d?(decode?g:md5(g))+" "+d:""}),i=a();g.push(i);var m=[];each(g,function(a){""!==a&&m.push(a)});return m.join("-")}return""}return"Microsoft Internet Explorer"===navigator.appName?b():a()}},{key:"sc",value:function(){var a;return a=""+(function(){var a="0";try{win.localStorage.BAIDU_POS_wh=
"@","@"===win.localStorage.BAIDU_POS_wh&&(a="1",win.localStorage.removeItem("BAIDU_POS_wh"))}catch(d){}return a}()+function(){var a="0";try{oPersistDiv.setAttribute("remember","@"),oPersistDiv.save("oXMLStore"),oPersistDiv.setAttribute("remember","!"),oPersistDiv.load("oXMLStore"),"@"==oPersistDiv.getAttribute("remember")&&(a="1")}catch(d){}return a}())}},{key:"im",value:function(){return+(void 0!==window.orientation)}},{key:"ui",value:function(){function a(){return Math.floor(65536*(1+Math.random())).toString(16).substring(1)}
function b(){return a()+a()+"-"+a()+"-"+a()+"-"+a()+"-"+a()+a()+a()}b=b();getCookieRaw("WHUUID")?b=getCookieRaw("WHUUID"):setCookieRaw("WHUUID",b);return b}},{key:"ci",value:function(){return getCookieRaw("CPROID")||""}},{key:"bi",value:function(){return getCookieRaw("BAIDUID")||""}},{key:"bp",value:function(){return getCookieRaw("BDUSS")||""}},{key:"wf",value:function(){return 0}}];function createFP(a){a=a.join("");return md5(a)}
function send(){if(!0===isSend)return!1;isSend=!0;generateStoreArray();var a=store,b=storeArray;1===sendMode?(a.br=getBrowser(),a.fp=createFP(b),log("http://eclick.baidu.com/wh.jpg?",a,!0)):2===sendMode&&log("http://eclick.baidu.com/wh.jpg?",{br:getBrowser(),fp:createFP(b),ci:store.ci,im:store.im,wf:store.wf?1:0},!0)}
function createFontsFlash(a){(function(){var a=navigator;if(a.plugins&&a.mimeTypes.length)return!!a.plugins["Shockwave Flash"];if(window.ActiveXObject&&!window.opera)for(a=12;2<=a;a--)try{if(new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+a))return!0}catch(d){}return!1})()&&(document.getElementById("oFlashDiv").innerHTML='<embed wmode="transparent" name="BAIDU_CLB_wh_o_flash" id="BAIDU_CLB_wh_o_flash" src="http://pos.baidu.com/wh/o.swf" swliveconnect="true" quality="high" width="1" height="1" align="middle" allowScriptAccess="samedomain" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer">');
win.fontList=function(b){font=md5(b);send();clearTimeout(a);send=function(){}};setTimeout(function d(){var a;a:{try{var g=document.getElementById("BAIDU_CLB_wh_o_flash");if(g&&"undefined"!=typeof g.GetVariable){var i=g.GetVariable("/:user_fonts");i&&win.fontList(i);a=!0;break a}}catch(m){}a=!1}if(!a&&!isSend)return setTimeout(d,250)},250)}
function generateStoreArray(){each(params,function(a){var b=a.key,a=a.value,a="function"===typeof a?a():a;store[b]="wf"===b?font:a;!0!=={ui:!0,ci:!0,bi:!0,bp:!0}[b]&&(storeArray.push(b),storeArray.push(":"),storeArray.push(store[b]),storeArray.push(";"))})}var sendMode=0,c=getCookieRaw("CPROID")||"",n=""===c?+new Date:parseInt(c.substring(8,20),16);
if(0===n%11||1===n%11||2===n%11||3===n%11||debug)sendMode=1;else if(0<navigator.userAgent.indexOf("Chrome")||"Microsoft Internet Explorer"===navigator.appName)sendMode=2;if(0!==sendMode){var sendLast=setTimeout(function(){isSend||send()},2E3);createFontsFlash(sendLast)};
})();