/*! ver:7o Copyright 2014 Baidu Inc. All Rights Reserved. */;(function(){var m=!0,o=!1;window.BAIDU_DUP_define&&window.BAIDU_DUP_define("clb/monitor7o",[],function(){return{sendLog:function(d){if(d=d.data&&d.data.monitorUrl){var f=new Image,i="log"+ +new Date;window[i]=f;f.onload=f.onerror=f.onabort=function(){f.onload=f.onerror=f.onabort=null;try{delete window[i]}catch(b){window[i]=void 0}};f.src=d}}}});
window.BAIDU_DUP_define&&window.BAIDU_DUP_define("clb/template7o",[],function(){function d(d){var b={'"':"&quot;",">":"&gt;","<":"&lt;","&":"&amp;"};return d.replace(/[\"<>\&]/g,function(a){return b[a]})}var f=/\{(\w+)\:(\w+)\}/g;return{a:function(i,b){return i.replace(f,function(a,c,e){a=b[c];switch(e){case "number":a=+a||0;break;case "boolean":a=!!a;break;case "html":a=d(a)}return a})}}});
window.BAIDU_DUP_define&&window.BAIDU_DUP_define("clb/material7o",["clb/template7o"],function(d){function f(b,a,c){if("string"===typeof b)return b;if(!b.type)return"";var e=i[b.type];return e?(b="string"===typeof e?d.a(e,b):e(b,a),c?b:"<!DOCTYPE html><body>"+b):""}var i={text:function(b){var a='<span style="word-wrap:break-word;"><a href="{clickUrl:string}" target="{target:string}" style="font-size:{size:number}{unit:string};color:{defaultColor:string};font-weight:{defaultBold:string};font-style:{defaultItalic:string};text-decoration:{defaultUnderline:string};"{events}>{text:string}</a></span>',
c=/\{events\}/;if(1===b.version)a=a.replace(c,"");else if(2===b.version)for(var a=a.replace(c," onmouseover=\"this.style.color='{hoverColor:string}';this.style.fontWeight='{hoverBold:string}';this.style.fontStyle='{hoverItalic:string}';this.style.textDecoration='{hoverUnderline:string}';\" onmouseout=\"this.style.color='{defaultColor:string}';this.style.fontWeight='{defaultBold:string}';this.style.fontStyle='{defaultItalic:string}';this.style.textDecoration='{defaultUnderline:string}';\""),c=["default",
"hover"],e=0;e<c.length;e++){var g=c[e],f=g+"Color",i=g+"Bold",j=g+"Italic",g=g+"Underline";b[f]="#"+b[f];b[i]=b[i]?"bold":"normal";b[j]=b[j]?"italic":"normal";b[g]=b[g]?"underline":"none"}return d.a(a,b)},image:'<a href="{clickUrl:string}" target="{target:string}"><img src="{src:string}" title="{title:html}" alt="{title:html}" border="0" height="{height:number}" width="{width:number}" /></a>',flash:function(b){b.file=b.hasLink?"cflash":"flash";b.imageClickUrl=b.clickUrl;b.hasLink||(b.clickUrl="");
return d.a('<script>var BD = BD || {};BD.MC = BD.MC || {};BD.MC.ADFlash = BD.MC.ADFlash || {};BD.MC.ADImg = BD.MC.ADImg || {};BD.MC.ADFlash.w = {width:number};BD.MC.ADFlash.h = {height:number};BD.MC.ADFlash.mu = "{src:string}";BD.MC.ADFlash.cu = "{clickUrl:string}";BD.MC.ADFlash.wm = {wmode:number};BD.MC.ADFlash.ct = "{clickTag:string}";BD.MC.ADImg.w = {imageWidth:number};BD.MC.ADImg.h = {imageHeight:number};BD.MC.ADImg.mu = "{imageSrc:string}";BD.MC.ADImg.cu = "{imageClickUrl:string}";BD.MC.ADImg.tw = "{target:string}";BD.MC.ADImg.flag = {backupImage:number};<\/script><script src ="http://cbjs.baidu.com/js/{file:string}.js"><\/script>',
b)},rich:function(b){return b.content},slide:function(b,a){for(var c=[],e=b.materials,g=0;g<e.length;g++){var i=e[g];"string"!==typeof i&&(i=f(i,a,m));c.push(i)}b.html="<div>"+c.join("</div><div>")+"</div>";b.width=a.width;b.height=a.height;return d.a('<div id="bd_ec_clb_asp" style="width:{width:number}px;height:{height:number}px;overflow:hidden;">{html:string}</div><script>(function(){var d = document;function G(id) { return d.getElementById(id); };var container = G("bd_ec_clb_asp");var pages = container.childNodes;var pl = 0;for (var i = 0; i < pages.length; i++) {if (pages[i].nodeType === 1) {pl++;}}var cp = 0;function showPage(pn) { pages[pn].style.display = ""; };function hidePages() {for (var i = 0; i < pl; i++) {pages[i].style.display = "none";}};function roll() {hidePages();showPage(cp);cp == (pages.length - 1) ? cp = 0 : cp++;};var autoRoll;function setRoll() { autoRoll = window.setInterval(function() { roll(); }, {interval:number});};roll();setRoll();container.onmouseover = function() { window.clearInterval(autoRoll); };container.onmouseout = function() {setRoll(); };})();<\/script>',
b)}};return{a:f}});
window.BAIDU_DUP_define&&window.BAIDU_DUP_define("clb/frame7o",["api"],function(d){function f(){var b=document.createElement("iframe"),a=o;b.src="about:blank";document.body.insertBefore(b,document.body.firstChild);try{a=!b.contentWindow.document}catch(c){a=m}document.body.removeChild(b);f=function(){return a};return a}function i(){return f()?d.getConfig("domainPolicyFileUrl")||"/domain-policy.htm":"about:blank"}d.defineOnce("BAIDU_DUP_CLB_renderFrame",function(b){var a=document.getElementById("baidu_clb_slot_iframe_"+b),
c=d.getSlots(b);if(c)if(f()&&a.getAttribute("src",2)!==i())a.src=i();else if(c&&!c.status.finish)try{d.setStatus(b,"finish");var e=d.getInfo("#"+b).html;0>e.indexOf("<body>")&&(e="<!DOCTYPE html><body>"+e);var g=a.contentWindow.document;g.open("text/html","replace");g.write(e);g.close();g.body&&(g.body.style.backgroundColor="transparent")}catch(n){d.addErrorItem(b,"PermissionDenied")}});return{l:function(){return f()},h:i,g:function(b,a){var c;c=a.id;c='<iframe id="baidu_clb_slot_iframe_'+c+'" src="'+
i()+'" onload="BAIDU_DUP_CLB_renderFrame(\''+c+'\')" width="'+a.width+'" height="'+a.height+'" vspace="0" hspace="0" allowTransparency="true" scrolling="no" marginWidth="0" marginHeight="0" frameborder="0" style="border:0; vertical-align:bottom; margin:0; display:block;"></iframe>';b.innerHTML=c}}});
window.BAIDU_DUP_define&&window.BAIDU_DUP_define("clb/logService7o",["api"],function(d){d.bind(window,"load",function(){window.BAIDU_DUP_require(["clb/detect"],function(){},m)})});
window.BAIDU_DUP_define&&window.BAIDU_DUP_define("clb/fixed7o",["api","clb/monitor7o","clb/material7o","clb/frame7o","clb/logService7o"],function(d,f,i,b){return{render:function(a,c){a={id:a.id,data:a._html,i:a._fxp,j:a._isMlt,width:a._w,height:a._h};f.sendLog(a);if(!a.data&&!a.i)d.setStatus(a.id,"finish");else{if(a.j&&"sync"===d.getFillType(a.id)){var e="string"===typeof a.data?a.data:a.data.content;if(e){d.setStatus(a.id,"finish");document.write(e);return}}if(!c)return null;var e=document.getElementById(c),
g=i.a(a.data,a,m);d.putInfo("#"+a.id,{html:g});b.g(e,a)}},validate:function(a){var b=a._stype,a=a._isMlt;return 0!==b&&3!==b||0!==a&&1!==a&&a!==o?o:m}}});
})();window.BAIDU_DUP_define&&window.BAIDU_DUP_define("clb/detect",["api"],function(g){function e(a){a.url="";a.host=window.location.hostname;a.from="DUP";g.sendLog({data:a,a:"now"})}try{setTimeout(function(){var a=g.getSlots(),c;for(c in a){var b=a[c],h=b.status;if(h.render){for(var d=b.errors,i=!1,f=0;f<d.length;f++)if("PermissionDenied"===d[f]){i=!0;break}d=b.response.data&&b.response.data._html;if(i)e({type:"renderFail",id:c,error:"PermissionDenied",empty:!!d});else if(h.finish){if(1!==b.response.data._isMlt&&
(b=document.getElementById("baidu_clb_slot_iframe_"+c)))try{var j=b.contentWindow.document.body;(!j||!j.firstChild)&&e({type:"renderEmpty",id:c})}catch(k){}}else e({type:"renderFail",id:c,error:"NotFilled",empty:!!d})}}},0)}catch(k){}});