/*! ver:1389599727 Copyright 2014 Baidu Inc. All Rights Reserved. */;(function(){var k=!0,m=null,o=!1,p=window.BAIDU_DUP2_require,C=window.BAIDU_DUP2_define;C&&C("nova/common/bom1389599727",[],function(){var f={};/msie (\d+\.\d)/i.test(navigator.userAgent)&&(f.b=document.documentMode||+RegExp.$1);/opera\/(\d+\.\d)/i.test(navigator.userAgent)&&(f.opera=+RegExp.$1);/firefox\/(\d+\.\d)/i.test(navigator.userAgent)&&(f.Ub=+RegExp.$1);/(\d+\.\d)?(?:\.\d)?\s+safari\/?(\d+\.\d+)?/i.test(navigator.userAgent)&&!/chrome/i.test(navigator.userAgent)&&(f.oc=+(RegExp.$1||RegExp.$2));/chrome\/(\d+\.\d)/i.test(navigator.userAgent)&&(f.Nb=+RegExp.$1);try{/(\d+\.\d)/.test(window.external.gc)&&
(f.hc=+RegExp.$1)}catch(i){}f.Pa=/webkit/i.test(navigator.userAgent);f.vb=/gecko/i.test(navigator.userAgent)&&!/like gecko/i.test(navigator.userAgent);f.Oa="CSS1Compat"==document.compatMode;return{f:f,u:function(){var a=k;if(this.f.b&&(7>this.f.b||"BackCompat"===document.compatMode))a=o;return a},$b:function(a){try{return a=a||window,"BackCompat"===a.document.compatMode?a.document.body.scrollWidth:a.document.documentElement.scrollWidth}catch(g){return 0}},Zb:function(a){try{return a=a||window,"BackCompat"===
a.document.compatMode?a.document.body.scrollHeight:a.document.documentElement.scrollHeight}catch(g){return 0}},ga:function(a){try{return a=a||window,"BackCompat"===a.document.compatMode?a.document.body.clientWidth:a.document.documentElement.clientWidth}catch(g){return 0}},K:function(a){try{return a=a||window,"BackCompat"===a.document.compatMode?a.document.body.clientHeight:a.document.documentElement.clientHeight}catch(g){return 0}},M:function(a){a=(a||window).document;return window.pageYOffset||a.documentElement.scrollTop||
a.body.scrollTop},La:function(a){a=(a||window).document;return window.pageXOffset||a.documentElement.scrollLeft||a.body.scrollLeft},Qa:function(a){var g=o;try{a&&"object"===typeof a&&a.document&&"setInterval"in a&&(g=k)}catch(b){g=o}return g},Q:function(a){a=a||window;return a!=window.top&&a!=a.parent||!this.Qa(a)},P:function(a,g){for(var g=2===arguments.length?g:a.parent,b=0;10>b++&&this.Q(a,g);){var h;try{h=!!a.parent.location.toString()}catch(e){h=o}if(!h)return k;a=a.parent}return 10<=b?k:o},
Cb:function(a,g){var b=new Image,h="cpro_log_"+Math.floor(2147483648*Math.random()).toString(36),g=g||window;g[h]=b;b.onload=b.onerror=b.onabort=function(){b.onload=b.onerror=b.onabort=m;b=g[h]=m};b.src=a},ha:function(a){if(!a)return document;"string"===typeof a&&(a=document.getElementById(a));return 9===a.nodeType?a:a.ownerDocument||a.document},ka:function(a){"string"===typeof a&&(a=document.getElementById(a));a=this.ha(a);return a.parentWindow||a.defaultView||m},bc:function(a){a=a||window;return this.Q(a)&&
!this.P(a,a.top)&&this.Qa(a.top)?a.top:a}}});
C&&C("nova/common/logic1389599727",[],function(){return{Sb:function(f){(f=f||"")&&(f=f.replace(/%u[\d|\w]{4}/g,function(f){return encodeURIComponent(unescape(f))}));return f},Ya:function(f,i){return f.replace(/{(.*?)}/g,function(a,g){return i[g]||""})},xb:function(f){return(new Function("return "+f))()},ja:function(f,i){if(f&&i){var a=f.match(RegExp("(^|&|\\?|#)"+i+"=([^&]*)(&|$)",""));if(a)return a[2]}return m},kc:function(f,i){var f=f||"",i=i||"?",a=arguments.callee;a.hasOwnProperty[i]||(a[i]={});a=a[i];
if(a.hasOwnProperty(f))return a[f];var g={},b=f.indexOf(i),h=f.substring(b+1).split("&");if(-1!==b)for(var b=0,e=h.length;b<e;b++){var d=h[b].split("="),c=decodeURIComponent(d[0]),d=decodeURIComponent(d[1]);g.hasOwnProperty(c)?(g[c].constructor!==Array&&(g[c]=[g[c]]),g[c].push(d)):g[c]=d}return a[f]=g}}});
C&&C("nova/common/cookie1389599727",[],function(){return{z:function(f,i){var a,g=RegExp("(^| )"+f+"=([^;]*)(;|$)").exec((i||window).document.cookie);g&&(a=g[2]);return a},sa:function(f,i,a){var a=a||{},g=a.w;"number"==typeof a.w&&(g=new Date,g.setTime(g.getTime()+a.w));document.cookie=""+f+"="+i+(a.path?"; path="+a.path:"")+(g?"; expires="+g.toGMTString():"")+(a.domain?"; domain="+a.domain:"")+(a.pc?"; secure":"")},remove:function(f){var i=new Date;i.setTime(i.getTime()-86400);this.qc(f,"",{path:"/",w:i})}}});
C&&C("nova/preview1389599727",["nova/common/bom1389599727","nova/common/logic1389599727","nova/common/cookie1389599727"],function(f,i,a){function g(b){b=decodeURIComponent(b).replace(/\\x1e/g,"&").replace(/\\x1d/g,"=").replace(/\\x1c/g,"?").replace(/\\x5c/g,"\\");return i.xb(b)}return{tb:function(b,h){var e=window.location.href,d=parseInt(b.rsi0),c=parseInt(b.rsi1),l=parseInt(b.at),q=o,s;s=e?e.substring(e.indexOf("?")):f.P(window)?window.location.search.slice(1):window.top.location.search.slice(1);var y=document.referrer,t=0<=h.indexOf("inlay")||
"ui"===h?"bd_cpro_prev":"bd_cpro_fprev",j="",A;try{A=document.cookie}catch(n){}-1!==s.indexOf(t)&&(j=i.ja(s,t));!j&&A&&-1!==A.indexOf(t)&&(j=a.z(t));!j&&-1!==y.indexOf(t)&&(j=i.ja(y,t));if(j)if(s=g(j),void 0===l&&(l=1),1!==parseInt(s.type)&&2===(l&2))q=parseInt(s.imgWidth)===parseInt(d)&&parseInt(s.imgHeight)===parseInt(c);else if(1===parseInt(s.type)&&(1===(l&1)||64===(l&64)||32===(l&32)))q=k;return q?(d=0<=h.indexOf("inlay")||"ui"===h?"bd_cpro_prev":"bd_cpro_fprev",e=i.ja(e,d),c=b.tn,l=g(e),q=m,
0<=h.indexOf("inlay")?q={serviceUrl:"http://cpro.baidu.com/cpro/ui/preview/templates/"+(1===parseInt(l.type)?c+".html":2===parseInt(l.type)?"image.html":4===parseInt(l.type)?"flash.html":"blank_tips.html"),paramString:(""+d+"=#"+e+"&ut="+ +new Date).replace(/\.(?!swf)/g,"%252e")}:"float"===h&&(l=parseInt(l.type),l="http://cpro.baidu.com/cpro/ui/preview/templates/"+(2===l?"float_image.html":4===l?"float_flash.html":"blank_tips.html"),e="tn="+c+("&"+d+"="+e).replace(/\./g,"%252e")+"&ut="+ +new Date,
q={serviceUrl:l,paramString:e}),q):m}}});
C&&C("nova/business/businessLogic1389599727",["nova/preview1389599727"],function(f){var i={inlay:4,"float":2,patch:1,linkunit:6},a={inlay:0,"float":0,patch:0,linkunit:0};return{Sa:function(a){var b=a._html||{},h="",e="http://pos.baidu.com/ecom",d=a.id.split("_")[0],c=a.sw,l=a.sh,q=a.displayType,s=b.tn||"",y=s.toLowerCase(),t=b.ch||0,a=a.qn||"",j=b.n||"",i=b.dai||0;b.dtm="BAIDU_DUP2_SETJSONADSLOT";b.dc="2";b.di=d;var h=[],n;for(n in b)n&&b.hasOwnProperty(n)&&h.push(""+n+"="+encodeURIComponent(b[n].toString()));h=h.join("&");
if((n=f.tb(b,q))&&void 0!==n.serviceUrl&&void 0!==n.paramString)e=n.serviceUrl,h=n.paramString;return{slotId:d,slotWidth:c,slotHeight:l,displayType:q,styleType:y,unionAccount:j,adIndex:i,channel:t,pvId:a,stuffType:"unknown",serviceUrl:e,paramString:h,delayIn:b.delayIn,delayOut:b.delayOut,sessionSync:b.sessionSync!==o&&"false"!==b.sessionSync,closeFor:b.closeFor,xuantingType:b.xuanting,tn:s}},na:function(a){var b={};b.jb=(a.jb||"pc").toLowerCase();b.v=(a.v||"inlay-fixed").toLowerCase();b.m=(a.m||"template_inlay_all_normal").toLowerCase();
b.ta=(a.ta||"text").toLowerCase();if(-1<b.m.indexOf("tlink")||-1<b.m.indexOf("linkunit"))b.v="linkunit-fixed";a=b.v.split("-");b.H=a[0]||"inlay";b.Qb=a[1]||"fixed";return b},Da:function(g){g=this.na(g);g=g.H;return a[g]<=i[g]},Xb:function(g){g=this.na(g);return a[g.H]},Ua:function(g){g=this.na(g);a[g.H]+=1;return k},Ma:function(a,b){var f=document.getElementById("cpro_"+a);f||(f=document.getElementById(b));return f}}});
C&&C("nova/painter/inlayFixed",["nova/business/businessLogic1389599727"],function(f){function i(a){return'<iframe width="{slotWidth}" height="{slotHeight}" src="{serviceUrl}?{paramString}" align="center,center" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" allowtransparency="true"></iframe>'.replace(/{(.*?)}/g,function(g,b){return a[b]||""})}return{render:function(a,g){a.displayType="inlay-fixed";var b=f.Sa(a),h={v:b.displayType,m:b.styleType,ta:b.stuffType};if(!f.Da(h))return o;f.Ma(b.slotId,
g).innerHTML=i(b);f.Ua(h);(function(){var a=b.slotId,d=b.adIndex||0;p(["viewWatch"],function(c){c.register({id:a,wrapperId:g,logType:"block",extra:"did="+d+"&ch="+b.channel+"&jk="+b.pvId+"&tn="+b.tn+"&n="+b.unionAccount+"&js=c"})},k)})()}}});
})();
