/*! ver:1389684067 Copyright 2014 Baidu Inc. All Rights Reserved. */;(function(){var k=!0,m=null,o=!1,p=window.BAIDU_DUP2_require,C=window.BAIDU_DUP2_define;
C&&C("nova/common/cookie1389684067",[],function(){return{z:function(f,i){var a,g=RegExp("(^| )"+f+"=([^;]*)(;|$)").exec((i||window).document.cookie);g&&(a=g[2]);return a},sa:function(f,i,a){var a=a||{},g=a.w;"number"==typeof a.w&&(g=new Date,g.setTime(g.getTime()+a.w));document.cookie=""+f+"="+i+(a.path?"; path="+a.path:"")+(g?"; expires="+g.toGMTString():"")+(a.domain?"; domain="+a.domain:"")+(a.pc?"; secure":"")},remove:function(f){var i=new Date;i.setTime(i.getTime()-86400);this.qc(f,"",{path:"/",w:i})}}});
C&&C("nova/common/bom1389684067",[],function(){var f={};/msie (\d+\.\d)/i.test(navigator.userAgent)&&(f.b=document.documentMode||+RegExp.$1);/opera\/(\d+\.\d)/i.test(navigator.userAgent)&&(f.opera=+RegExp.$1);/firefox\/(\d+\.\d)/i.test(navigator.userAgent)&&(f.Ub=+RegExp.$1);/(\d+\.\d)?(?:\.\d)?\s+safari\/?(\d+\.\d+)?/i.test(navigator.userAgent)&&!/chrome/i.test(navigator.userAgent)&&(f.oc=+(RegExp.$1||RegExp.$2));/chrome\/(\d+\.\d)/i.test(navigator.userAgent)&&(f.Nb=+RegExp.$1);try{/(\d+\.\d)/.test(window.external.gc)&&
(f.hc=+RegExp.$1)}catch(i){}f.Pa=/webkit/i.test(navigator.userAgent);f.vb=/gecko/i.test(navigator.userAgent)&&!/like gecko/i.test(navigator.userAgent);f.Oa="CSS1Compat"==document.compatMode;return{f:f,u:function(){var a=k;if(this.f.b&&(7>this.f.b||"BackCompat"===document.compatMode))a=o;return a},$b:function(a){try{return a=a||window,"BackCompat"===a.document.compatMode?a.document.body.scrollWidth:a.document.documentElement.scrollWidth}catch(g){return 0}},Zb:function(a){try{return a=a||window,"BackCompat"===
a.document.compatMode?a.document.body.scrollHeight:a.document.documentElement.scrollHeight}catch(g){return 0}},ga:function(a){try{return a=a||window,"BackCompat"===a.document.compatMode?a.document.body.clientWidth:a.document.documentElement.clientWidth}catch(g){return 0}},K:function(a){try{return a=a||window,"BackCompat"===a.document.compatMode?a.document.body.clientHeight:a.document.documentElement.clientHeight}catch(g){return 0}},M:function(a){a=(a||window).document;return window.pageYOffset||a.documentElement.scrollTop||
a.body.scrollTop},La:function(a){a=(a||window).document;return window.pageXOffset||a.documentElement.scrollLeft||a.body.scrollLeft},Qa:function(a){var g=o;try{a&&"object"===typeof a&&a.document&&"setInterval"in a&&(g=k)}catch(b){g=o}return g},Q:function(a){a=a||window;return a!=window.top&&a!=a.parent||!this.Qa(a)},P:function(a,g){for(var g=2===arguments.length?g:a.parent,b=0;10>b++&&this.Q(a,g);){var h;try{h=!!a.parent.location.toString()}catch(e){h=o}if(!h)return k;a=a.parent}return 10<=b?k:o},
Cb:function(a,g){var b=new Image,h="cpro_log_"+Math.floor(2147483648*Math.random()).toString(36),g=g||window;g[h]=b;b.onload=b.onerror=b.onabort=function(){b.onload=b.onerror=b.onabort=m;b=g[h]=m};b.src=a},ha:function(a){if(!a)return document;"string"===typeof a&&(a=document.getElementById(a));return 9===a.nodeType?a:a.ownerDocument||a.document},ka:function(a){"string"===typeof a&&(a=document.getElementById(a));a=this.ha(a);return a.parentWindow||a.defaultView||m},bc:function(a){a=a||window;return this.Q(a)&&
!this.P(a,a.top)&&this.Qa(a.top)?a.top:a}}});
C&&C("nova/common/oo1389684067",[],function(){function f(b){var a=f.create(f);return b.call(a,a,a.Aa)}function i(b,a){if(b.constructor===Array)for(var e=0,d=b.length;e<d;e++){if(a.call(b,b[e],e,b)===o)return o}else{var e=!{toString:1}.propertyIsEnumerable("toString"),c="toString,toLocaleString,valueOf,constructor,propertyIsEnumerable,hasOwnProperty,isPrototypeOf".split(",");for(d in b)if(b.hasOwnProperty(d)&&a.call(b,b[d],d,b)===o)return o;if(e){e=0;for(d=c.length;e<d;e++){var l=c[e];if(b.hasOwnProperty(l)&&
a.call(b,l,e,b)===o)return o}}}return k}function a(b,a,e){i(a,function(a,c){if(!b.hasOwnProperty(c)||e)b[c]=a})}function g(b){function a(){}if(Object.create)return Object.create(b);a.prototype=b;return new a}f.Aa={};f.create=g;f.Ha=i;f.za=function(b,g){var e=b.hasOwnProperty("constructor")?b.constructor:function(){};e.prototype=b;e.prototype.constructor=e;g=g||{};g.V&&a(e,g.V);return e};f.extend=function(b,h,e){var d;d=h.hasOwnProperty("constructor")?h.constructor:function(){b.constructor.apply(this,
arguments)};d.prototype=g(b.prototype);a(d.prototype,h,k);d.prototype.constructor=d;d.prototype.Lb=b.prototype;a(d,b);e=e||{};e.V&&a(d,e.V,k);return d};f.jc=function(b){var a=this.Aa;i(b.split("."),function(b){a.hasOwnProperty(b)||(a[b]={});a=a[b]});return a};f.i=function(a,g){var e;return function(){e=e||[];for(var d=0,c=arguments.length;d<c;d++)e.push(arguments[d]);return a.apply(g||{},e)}};return f});
C&&C("nova/common/dom1389684067",["nova/common/oo1389684067","nova/common/bom1389684067"],function(f,i){return f(function(a){var g=i.f;return{Wb:function(b,h){return"string"===typeof b||b instanceof String?(h||window).document.getElementById(b):b},Na:function(b,h){var e=k;if("string"===typeof h)return b.id===h;if(h.constructor===Object)return a.Ha(h,function(c,h){var d=(b.getAttribute?b.getAttribute(h):b[h])||b[h];if("tagName"===h){if(d.toUpperCase()!=c.toUpperCase())return e=o}else if(d!=c)return e=o}),e;if(h.constructor===Array){var d=
h.concat([]);d.reverse();for(var c=b;c&&d.length;c=c.parentNode)this.Na(c,d[0])&&d.shift();return!d.length?k:o}},$a:function(b,h){if(b&&h(b)!==o){var a=b.childNodes;if(a)for(var d=0,c=a.length;d<c;d++)if(this.$a(a[d],h)===o)return o}},Xa:function(b,h){var a=this;b.constructor===Object&&(b=this.d(b));if("string"===typeof h){for(var d=document.getElementById(h),c=d;c;){if(c===b)return d;c=c.parentNode}return m}if(h.constructor===Object){var l=m;a.$a(b,function(c){if(a.Na(c,h))return l=c,o});return l}},
d:function(b){if(b){if(b.nodeName)return b;1<arguments.length&&(b=Array.prototype.slice.call(arguments,0));if("string"===typeof b)return document.getElementById(b);if(b.constructor===Object)return this.Xa(document.documentElement,b);if(b.constructor===Array){for(var h=b.concat([]),a=document.documentElement;h.length&&a;)a=this.Xa(a,h.shift());return a}}},zb:function(b,h,e){var e=e||this.cb||window,d=e.document;this.Ga=0;this.t=this.t||[];this.t.push({fa:b,Fa:h||0,ca:o});var c=a.i(function(){var c=
o;this.Ga++;var b=o;try{e.frameElement&&(b=k)}catch(a){b=k}if(g.b&&9>g.b&&!b)try{d.documentElement.doScroll("left"),c=k}catch(h){}else if("complete"===d.readyState||this.kb)c=k;else if(3E5<this.Ga){this.o&&(e.clearInterval(this.o),this.o=m);return}if(c)try{if(this.t&&this.t.length)for(var c=0,f=this.t.length;c<f;c++){var j=this.t[c];j&&j.fa&&!j.ca&&(j.Fa?(j.ca=k,e.setTimeout(j.fa,j.Fa)):(j.ca=k,j.fa()))}}catch(i){throw i;}finally{this.o&&(e.clearInterval(this.o),this.o=m)}},this),b=a.i(function(){this.kb=
k;c()},this);this.o||(this.o=e.setInterval(c,50),d.addEventListener?(d.addEventListener("DOMContentLoaded",b,o),e.addEventListener("load",b,o)):d.attachEvent&&e.attachEvent("onload",b,o))},u:function(){var b=k;if(g.b&&(7>g.b||"BackCompat"===document.compatMode))b=o;return b},bind:function(b,a,e){"string"===typeof b&&(b=this.d(b));a=a.replace(/^on/i,"").toLowerCase();b.addEventListener?b.addEventListener(a,e,o):b.attachEvent&&b.attachEvent("on"+a,e);return b},sc:function(b,a,e){b=this.d(b);a=a.replace(/^on/i,
"").toLowerCase();b.removeEventListener?b.removeEventListener(a,e,o):b.detachEvent&&b.detachEvent("on"+a,e);return b},g:function(b,a){var e;"string"===typeof b&&(b=this.d(b));var d=i.ha(b),c="",c=-1<a.indexOf("-")?a.replace(/[-_][^-_]{1}/g,function(c){return c.charAt(1).toUpperCase()}):a.replace(/[A-Z]{1}/g,function(c){return"-"+c.charAt(0).toLowerCase()});d&&d.defaultView&&d.defaultView.getComputedStyle?((d=d.defaultView.getComputedStyle(b,m))&&(e=d.getPropertyValue(a)),"boolean"!==typeof e&&!e&&
(e=d.getPropertyValue(c))):b.currentStyle&&((d=b.currentStyle)&&(e=d[a]),"boolean"!==typeof e&&!e&&(e=d[c]));return e},sb:function(b,a){a=a||window;"string"===typeof b&&(b=this.d(b));if(b){for(var e=this.L(b),d,c=0;a!=a.parent&&10>c;)c++,d=this.L(a.frameElement),e.left+=d.left,e.top+=d.top,a=a.parent;return e}},L:function(b){"string"===typeof b&&(b=this.d(b));var a=i.ha(b),e=i.f;0<e.vb&&a.getBoxObjectFor&&this.g(b,"position");var d={left:0,top:0},c;if(b==(e.b&&!e.Oa?a.body:a.documentElement)||!b)return d;
if(b.getBoundingClientRect)b=b.getBoundingClientRect(),d.left=Math.floor(b.left)+Math.max(a.documentElement.scrollLeft,a.body.scrollLeft),d.top=Math.floor(b.top)+Math.max(a.documentElement.scrollTop,a.body.scrollTop),d.left-=a.documentElement.clientLeft,d.top-=a.documentElement.clientTop,b=a.body,a=parseInt(this.g(b,"borderLeftWidth"),10),b=parseInt(this.g(b,"borderTopWidth"),10),e.b&&!e.Oa&&(d.left-=isNaN(a)?2:a,d.top-=isNaN(b)?2:b);else{c=b;do{d.left+=c.offsetLeft;d.top+=c.offsetTop;if(0<e.Pa&&
"fixed"==this.g(c,"position")){d.left+=a.body.scrollLeft;d.top+=a.body.scrollTop;break}c=c.offsetParent}while(c&&c!=b);if(0<e.opera||0<e.Pa&&"absolute"==this.g(b,"position"))d.top-=a.body.offsetTop;for(c=b.offsetParent;c&&c!=a.body;){d.left-=c.scrollLeft;if(!e.opera||"TR"!=c.tagName)d.top-=c.scrollTop;c=c.offsetParent}}return d},rb:function(b,a){var b=this.d(b),e=b.offsetWidth;if(a||o)var d=this.g(b,"marginLeft").toString().toLowerCase().replace("px","").replace("auto","0"),c=this.g(b,"marginRight").toString().toLowerCase().replace("px",
"").replace("auto","0"),e=e+(parseInt(d||0)+parseInt(c||0));return e},qb:function(b,a){var b=this.d(b),e=b.offsetHeight;if(a||o)var d=this.g(b,"marginTop").toString().toLowerCase().replace("px","").replace("auto","0"),c=this.g(b,"marginBottom").toString().toLowerCase().replace("px","").replace("auto","0"),e=e+(parseInt(d||0)+parseInt(c||0));return e},ac:function(b){var b=this.d(b),a=this.ka(b),e=0;if(this.Q(window)&&!i.P(window)){for(;a.parent!=window.top&&10>e;)e++,a=a.parent;10>e&&(b=a.frameElement||
b)}return b},Ka:function(b){var a=this.d(b),b=this.ka(a),e=100,d;try{for(;a&&a.tagName;){d=100;if(this.f.b){if(5<this.f.b)try{d=a.Tb.alpha.opacity||100}catch(c){}e=e>d?d:e}else{try{d=100*(b.getComputedStyle(a,m).opacity||1)}catch(l){}e*=d/100}a=a.parentNode}}catch(q){}return e||100},Yb:function(b){for(var a=this.d(b),b=this.ka(a),a=this.Ka(a),e=100,d=0;this.Q(b);){d++;if(i.P(b,b.parent))break;else e=100,b.frameElement&&(e=this.Ka(b.frameElement)),a*=e/100;b=b.parent}return a}}})});
C&&C("nova/common/logic1389684067",[],function(){return{Sb:function(f){(f=f||"")&&(f=f.replace(/%u[\d|\w]{4}/g,function(f){return encodeURIComponent(unescape(f))}));return f},Ya:function(f,i){return f.replace(/{(.*?)}/g,function(a,g){return i[g]||""})},xb:function(f){return(new Function("return "+f))()},ja:function(f,i){if(f&&i){var a=f.match(RegExp("(^|&|\\?|#)"+i+"=([^&]*)(&|$)",""));if(a)return a[2]}return m},kc:function(f,i){var f=f||"",i=i||"?",a=arguments.callee;a.hasOwnProperty[i]||(a[i]={});a=a[i];
if(a.hasOwnProperty(f))return a[f];var g={},b=f.indexOf(i),h=f.substring(b+1).split("&");if(-1!==b)for(var b=0,e=h.length;b<e;b++){var d=h[b].split("="),c=decodeURIComponent(d[0]),d=decodeURIComponent(d[1]);g.hasOwnProperty(c)?(g[c].constructor!==Array&&(g[c]=[g[c]]),g[c].push(d)):g[c]=d}return a[f]=g}}});
C&&C("nova/preview1389684067",["nova/common/bom1389684067","nova/common/logic1389684067","nova/common/cookie1389684067"],function(f,i,a){function g(b){b=decodeURIComponent(b).replace(/\\x1e/g,"&").replace(/\\x1d/g,"=").replace(/\\x1c/g,"?").replace(/\\x5c/g,"\\");return i.xb(b)}return{tb:function(b,h){var e=window.location.href,d=parseInt(b.rsi0),c=parseInt(b.rsi1),l=parseInt(b.at),q=o,s;s=e?e.substring(e.indexOf("?")):f.P(window)?window.location.search.slice(1):window.top.location.search.slice(1);var y=document.referrer,t=0<=h.indexOf("inlay")||
"ui"===h?"bd_cpro_prev":"bd_cpro_fprev",j="",A;try{A=document.cookie}catch(n){}-1!==s.indexOf(t)&&(j=i.ja(s,t));!j&&A&&-1!==A.indexOf(t)&&(j=a.z(t));!j&&-1!==y.indexOf(t)&&(j=i.ja(y,t));if(j)if(s=g(j),void 0===l&&(l=1),1!==parseInt(s.type)&&2===(l&2))q=parseInt(s.imgWidth)===parseInt(d)&&parseInt(s.imgHeight)===parseInt(c);else if(1===parseInt(s.type)&&(1===(l&1)||64===(l&64)||32===(l&32)))q=k;return q?(d=0<=h.indexOf("inlay")||"ui"===h?"bd_cpro_prev":"bd_cpro_fprev",e=i.ja(e,d),c=b.tn,l=g(e),q=m,
0<=h.indexOf("inlay")?q={serviceUrl:"http://cpro.baidu.com/cpro/ui/preview/templates/"+(1===parseInt(l.type)?c+".html":2===parseInt(l.type)?"image.html":4===parseInt(l.type)?"flash.html":"blank_tips.html"),paramString:(""+d+"=#"+e+"&ut="+ +new Date).replace(/\.(?!swf)/g,"%252e")}:"float"===h&&(l=parseInt(l.type),l="http://cpro.baidu.com/cpro/ui/preview/templates/"+(2===l?"float_image.html":4===l?"float_flash.html":"blank_tips.html"),e="tn="+c+("&"+d+"="+e).replace(/\./g,"%252e")+"&ut="+ +new Date,
q={serviceUrl:l,paramString:e}),q):m}}});
C&&C("nova/business/businessLogic1389684067",["nova/preview1389684067"],function(f){var i={inlay:4,"float":2,patch:1,linkunit:6},a={inlay:0,"float":0,patch:0,linkunit:0};return{Sa:function(a){var b=a._html||{},h="",e="http://pos.baidu.com/ecom",d=a.id.split("_")[0],c=a.sw,l=a.sh,q=a.displayType,s=b.tn||"",y=s.toLowerCase(),t=b.ch||0,a=a.qn||"",j=b.n||"",i=b.dai||0;b.dtm="BAIDU_DUP2_SETJSONADSLOT";b.dc="2";b.di=d;var h=[],n;for(n in b)n&&b.hasOwnProperty(n)&&h.push(""+n+"="+encodeURIComponent(b[n].toString()));h=h.join("&");
if((n=f.tb(b,q))&&void 0!==n.serviceUrl&&void 0!==n.paramString)e=n.serviceUrl,h=n.paramString;return{slotId:d,slotWidth:c,slotHeight:l,displayType:q,styleType:y,unionAccount:j,adIndex:i,channel:t,pvId:a,stuffType:"unknown",serviceUrl:e,paramString:h,delayIn:b.delayIn,delayOut:b.delayOut,sessionSync:b.sessionSync!==o&&"false"!==b.sessionSync,closeFor:b.closeFor,xuantingType:b.xuanting,tn:s}},na:function(a){var b={};b.jb=(a.jb||"pc").toLowerCase();b.v=(a.v||"inlay-fixed").toLowerCase();b.m=(a.m||"template_inlay_all_normal").toLowerCase();
b.ta=(a.ta||"text").toLowerCase();if(-1<b.m.indexOf("tlink")||-1<b.m.indexOf("linkunit"))b.v="linkunit-fixed";a=b.v.split("-");b.H=a[0]||"inlay";b.Qb=a[1]||"fixed";return b},Da:function(g){g=this.na(g);g=g.H;return a[g]<=i[g]},Xb:function(g){g=this.na(g);return a[g.H]},Ua:function(g){g=this.na(g);a[g.H]+=1;return k},Ma:function(a,b){var f=document.getElementById("cpro_"+a);f||(f=document.getElementById(b));return f}}});
C&&C("nova/painter/xuanting1389684067","nova/common/cookie1389684067,nova/common/bom1389684067,nova/common/dom1389684067,nova/common/logic1389684067,nova/common/oo1389684067,nova/business/businessLogic1389684067".split(","),function(f,i,a,g,b,h){var e;b(function(b){e=b.za({constructor:function(c){var b=c.a.id;this.a=a.d(c.a);this.type=+c.type;this.src=c.src;this.width=c.width;this.height=c.height;this.m=c.m||"";this.ua=c.ua||"";this.ba=c.ba||"0";this.xa=c.xa||"";this.pa=c.pa||"";this.C=this.wa=5;this.ma=c.ma;this.ra=c.ra;this.h=c.h;this.q="bd_close_"+this.h;this.ab=
!!f.z(this.q);this.l=this.ia(this.h);this.c=b;this.j="";this.fileName="c";this.aa=c.aa||0;2===this.type?this.j="top":3===this.type&&(this.j="bottom");this.j&&(this.bb=k,this.F=+c.F||0,this.G=+c.G||0,this.A=!!c.A||o,this.p=+c.p||0,this.fb=500);this.S=c.S||o},cc:function(c){return"string"===typeof c?document.getElementById(c):c},Gb:function(c,a){return(a||document).getElementsByTagName(c)[0]},Za:function(c,a){return c.replace(/\{(.*?)\}/g,function(c,b){return a.hasOwnProperty(b)?a[b]:c})},ia:function(c){var a=
{};return function(){a.hasOwnProperty(c)||(a[c]=0);++a[c];return"cproIframe"+a[c]}}(),f:i.f,Db:function(){var a={path:""};if(this.p&&!this.A){var b=new Date;b.setTime(b.getTime()+this.p);a.w=b}f.sa(this.q,1,a)},Bb:function(a){var b=new Date;b.setTime(b.getTime()-86400);f.sa(a,"",{path:"/",w:b})},U:function(){this.clientWidth=i.ga(window);this.clientHeight=i.K(window);this.j&&(this.e&&(this.e.style.width=this.clientWidth+"px"),this.ya&&(this.ya.style.width=this.clientWidth+"px"));this.B&&clearTimeout(this.B);
this.B=setTimeout(b.i(this.la,this),5)},la:function(){var c=this.e;if(c)if(a.u()){if(c.style.zIndex=2147483646,1===this.type)if("fixed"==c.style.position)this.Ba(),this.gb()&&(c.style.cssText=m,this.Ab());else{var b=this.Ib();b&&(this.Ea(),c.style.position="fixed",c.style.top=b+"px",this.Ba())}}else this.T(this.e)},gb:function(a){var b;a?(b=document.getElementById(a),a=document.getElementById(""+a+"placeholder")):(b=this.e||document.getElementById(this.c),a=document.getElementById(""+this.c+"placeholder"));
return b&&a&&(a=this.k(a).Z,this.k(b).Z<=a)?k:o},Ba:function(a){var b;a?(b=document.getElementById(a),a=document.getElementById(""+a+"placeholder")):(b=this.e||document.getElementById(this.c),a=document.getElementById(""+this.c+"placeholder"));b&&a&&(a=this.k(a).left,b.style.left=a+"px")},k:function(c){var b=a.L(c),e=i.La(window),d=i.M(window),g=a.rb(c,o),c=a.qb(c,o);return{top:b.top-d,bottom:b.top-d+c,left:b.left-e,right:b.left-e+g,Z:b.top,Mb:b.top+c,R:b.left,mc:b.left+g}},T:function(){this.clientWidth=
i.ga(window);this.clientHeight=i.K(window);var b=i.M(window),e=a.g(document.body,"position").toString(),d=a.L(document.body),g=d.left,h=d.top;if(d=this.e)if(d.style.position="absolute",d.style.zIndex=2147483646,1===this.type)if(document.getElementById(""+this.c+"placeholder")){var f=document.getElementById(""+this.c+"placeholder"),j=this.k(f);d.style.top=""+b+this.C+"px";d.style.left=""+j.R+"px";"relative"==e&&(d.style.top=b+this.C-h+"px",d.style.left=j.R-g+"px");d.style.visibility="visible";b=this.k(d);
j.Z>=b.Z&&(d.parentNode.removeChild(d),f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),d.style.cssText=m)}else{if(f=this.Jb(this.c))this.C=f,this.Ea(this.c),f=document.getElementById(""+this.c+"placeholder"),j=this.k(f),d.parentNode.removeChild(d),document.body.appendChild(d),d.style.zIndex=2147483646,d.style.top=b+this.C+"px",d.style.left=j.R+"px","relative"==e&&(d.style.top=b+this.C-h+"px",d.style.left=j.R-g+"px"),d.style.visibility="visible",d.style.position="absolute"}else 2===this.type?
d.style.top=b+"px":3===this.type&&(d.style.top=b+this.clientHeight-(this.height+10)+"px")},qa:function(){if(!this.S){var b=this.type,d=this.width,e=this.height,f={srcAttrName:void 0===b||1==b?"src":"_src",iframeWidth:d,iframeHeight:e,iframeId:this.l,paramString:this.ma||"",serviceUrl:this.ra};this.yb();var g=o;if(b&&(1===b||2===b||3===b)){var h=g="auto",i;if(1===b)i="inline-block",g=d+"px",h=e+"px";else if(2===b||3===b)i="block",g="100%",h=+e+10+"px";f.widthValue=g;f.heightValue=h;f.displayValue=
i;b=this.a;b.setAttribute("width",g);b.setAttribute("height",h);b.style.cssText=this.Za("width:{widthValue};height:{heightValue};display:{displayValue};",f);g=k}f=this.Za('<iframe id="{iframeId}" {srcAttrName}="{serviceUrl}?{paramString}" width="{iframeWidth}" height="{iframeHeight}" align="center,center" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" allowtransparency="true" ></iframe>',f);this.a.innerHTML=f;this.N=a.d(this.l);g&&(this.e=this.N.parentNode);this.ib();this.Kb()}},
ib:function(){var b=this.type,d=this.N,e=this.e;if(b){var f=1;if(2===b)f=2;else if(3===b)f=1;else if(1!==b&&0!==b&&this.e){this.e.style.display="none";return}var g=2===b||3===b,h="";switch(b){case 2:case 3:var h="display:none;",j="";this.f.b&&7>this.f.b&&(j="_background-image:none;_filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://cpro.baidustatic.com/cpro/ui/noexpire/img/toggle_btn_bk"+f+".png');");f=g?'<div id="'+this.l+'WrapToggle" style="z-index:2147483646;cursor:pointer;position:absolute;right:0;'+
this.j+':0;width:40px;height:100%;background-color:#3f3f3f;"><div style="width:20px;height:22px;position:absolute;top:50%;margin-top:-11px;left:50%;margin-left:-10px;background:no-repeat url(http://cpro.baidustatic.com/cpro/ui/noexpire/img/toggle_btn_bk'+f+".png);"+j+'"></div></div>':"";g=g?'<div id="'+this.l+'WrapBk" style="'+this.j+':0;left:0;position:absolute;width:100%;height:100%;background-color:#666;-moz-opacity:.6;filter:alpha(opacity=60);opacity:.6;"></div>':"";j="";a.u()?1===b?j="position:fixed;top:0;":
2===b?j="position:fixed;top:0;width:100%;":3===b&&(j="position:fixed;bottom:0;width:100%;"):1===b?j="position:absolute;top:0;":2===b?j="position:absolute;top:0;width:100%;":3===b&&(j="position:absolute;top:"+(i.M(window)+i.K(window)-this.width)+"px;width:100%;");e.insertAdjacentHTML("afterBegin",g+f);e.style.cssText=[h,"height:",this.height+10,"px;right:0;z-index:2147483646;text-align:center;font-size:0;_overflow-y:hidden;",j].join("");d.style.cssText="position:relative;margin:5px 0;";this.va=a.d(""+
this.l+"WrapToggle");this.Y=this.Gb("DIV",this.va);this.ya=a.d(this.l+"WrapBk");this.U()}}},Wa:function(){var a=this.h,b=this.c,d=this;p(["viewWatch"],function(e){e.register({id:a,wrapperId:b,logType:"block",extra:"did="+d.aa+"&ch="+d.ba+"&jk="+d.pa+"&tn="+d.ua+"&n="+d.xa+"&js="+d.fileName})},k)},Kb:function(){var c=this,e=c.e,f=c.type,g=c.N,c=this;this.j?this.ab?e.parentNode.removeChild(e):(setTimeout(function(){e.style.display="block";if(2===f||3===f){var a=g.getAttribute("_src");a&&(g.setAttribute("src",
a),g.removeAttribute("_src"),c.Wa())}},this.F),this.G&&setTimeout(function(){e.style.display="none"},this.F+this.G)):this.Wa();this.va&&(2===this.type||3===this.type)&&a.bind(this.va,"click",b.i(this.Hb,this));a.bind(window,"scroll",b.i(this.la,this));a.bind(window,"resize",b.i(this.la,this))},yb:function(){for(var a=1;2>=a;a++)(function(a){var b="bkimg_"+ +new Date+Math.floor(1E5*Math.random()),c=window[b]=new Image;c.onload=c.onerror=function(){c.onload=c.onerror=m;c=window[b]=m};c.src="http://cpro.baidustatic.com/cpro/ui/noexpire/img/toggle_btn_bk"+
a+".png"})(a)},Hb:function(){this.bb?this.ub():this.show()},Va:function(a){if(!this.Ca){this.Ca=k;var b=this.e,d=this.ya,e=this.N,f=this.j,g=b.offsetHeight,h=Math.round(this.fb/g),i=0,n=this;a&&(b.style.width="100%");var v=+new Date,x=setInterval(function(){var b=i=Math.round((+new Date-v)/h),l=b;a&&(l=g-b);d.style[f]=-l+"px";e.style[f]=-l+"px";b>=g&&(n.Ca=o,(n.bb=a)&&"top"===f||!a&&"bottom"===f?n.f.b&&7>n.f.b?n.Y.style.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://cpro.baidustatic.com/cpro/ui/noexpire/img/toggle_btn_bk2.png');":
n.Y.style.backgroundImage="url(http://cpro.baidustatic.com/cpro/ui/noexpire/img/toggle_btn_bk2.png)":n.f.b&&7>n.f.b?n.Y.style.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://cpro.baidustatic.com/cpro/ui/noexpire/img/toggle_btn_bk1.png');":n.Y.style.backgroundImage="url(http://cpro.baidustatic.com/cpro/ui/noexpire/img/toggle_btn_bk1.png)",l=g,a&&(l=0),d.style[f]=-l+"px",e.style[f]=-l+"px",clearInterval(x))},h)}},show:function(){(this.A||this.p)&&this.Bb(this.q);this.Va(k)},ub:function(){(this.A||
this.p)&&this.Db();this.Va(o)},Ea:function(a){var b;a?(b=document.getElementById(a),a+="placeholder"):(b=this.e||document.getElementById(this.c),a=this.c+"placeholder");var d=document.createElement("div");d.id=a;d.align&&(d.align=b.getAttribute("align"));d.style.width=""+parseInt(b.getAttribute("width"),10)+"px";d.style.height=""+parseInt(b.getAttribute("height"),10)+"px";d.style.margin="0";d.style.padding="0";d.style.background="none";d.style.border="none";1===this.type&&(d.style.display="inline-block");
b.parentNode.insertBefore(d,b);return k},Ab:function(a){a=document.getElementById(a?a+"placeholder":this.c+"placeholder");a.parentNode.removeChild(a);return k},Ib:function(a){var b=this.wa;return this.k(a?document.getElementById(a):this.e||document.getElementById(this.c)).top<b?b:o},Jb:function(a){var b=this.wa;return this.k(a?document.getElementById(a):this.e||document.getElementById(this.c)).top<b?b:o}})});return{render:function(a,b){switch(parseInt(a._html.xuanting)){case 1:a.displayType="inlay-float";
break;case 2:a.displayType="float-top";break;case 3:a.displayType="float-bottom";break;default:a.displayType="inlay-float"}var f=h.Sa(a),g={v:f.displayType,m:f.styleType,ta:f.stuffType};if(!h.Da(g))return o;(new e({a:h.Ma(f.slotId,b),h:f.slotId,type:f.xuantingType,src:"",width:f.slotWidth,height:f.slotHeight,m:f.styleType,ua:f.tn,ba:f.channel,xa:f.unionAccount,aa:f.adIndex,pa:f.pvId,F:f.delayIn,G:f.delayOut,A:f.sessionSync,p:f.closeFor,ma:f.paramString,ra:f.serviceUrl})).qa();h.Ua(g)}}});})();
