;(function(global){
	global.Ta=global.Ta||{};
	Ta.hack=function(){
		return {params:'',
			conf:{sid:9877547,pf:2,hot:{}}		};
	};
})(this);

(function(h,r){function w(d){return(d=document.cookie.match(RegExp("(?:^|;\\s)"+d+"=(.*?)(?:;\\s|$)")))?d[1]:""}function x(d,a,b){var d=d+"="+a+";path=/;domain=",a=window.location.host,c={"com.cn":1,"net.cn":1,"gov.cn":1,"com.hk":1},e=a.split(".");2<e.length&&(a=(c[e.slice(-2).join(".")]?e.slice(-3):e.slice(-2)).join("."));document.cookie=d+a+(b?";expires="+b:"")}function s(d){var a,b,c,e={};void 0===d?(c=window.location,d=c.host,a=c.pathname,b=c.search.substr(1),c=c.hash):(c=d.match(/\w+:\/\/((?:[\w-]+\.)+\w+)(?:\:\d+)?(\/[^\?\\\"\'\|\:<>]*)?(?:\?([^\'\"\\<>#]*))?(?:#(\w+))?/i)||
[],d=c[1],a=c[2],b=c[3],c=c[4]);if(b)for(var h=b.split("&"),l=0,o=h.length;l<o;l++){var m=h[l].split("=");e[m[0]]=m[1]}return{host:d,path:a,search:b,hash:c,param:e}}function y(d){return(d||"")+Math.round(2147483647*(Math.random()||0.5))*+new Date%1E10}function z(d,a){var b=document.createElement("script"),c=document.getElementsByTagName("script")[0];b.src=d;b.type="text/javascript";b.onload=b.onerror=b.onreadystatechange=function(){/loaded|complete|undefined/.test(b.readyState)&&(b.onload=b.onerror=
b.onreadystatechange=null,b.parentNode.removeChild(b),b=void 0,a())};c.parentNode.insertBefore(b,c)}function v(d){d=d||{};if(d.conf){var a=d.conf,b;for(b in a)a.hasOwnProperty(b)&&(h[b]=a[b])}if(h.sid&&!Ta[h.sid]){a=[];b=0;var c=s(),c={dm:c.host,pvi:"",si:"",url:c.path,arg:encodeURIComponent(c.search||""),ty:1},e=w("pgv_pvi");e||(c.ty=0,e=y(),x("pgv_pvi",e,"Sun, 18 Jan 2038 00:00:00 GMT;"));c.pvi=e;e=w("pgv_si");e||(e=y("s"),x("pgv_si",e));c.si=e;var e=s(document.referrer),q=s(),e={rdm:e.host,rurl:e.path,
rarg:encodeURIComponent(e.search||""),adt:q.param.ADTAG||q.param.adtag},q={r2:h.sid,r3:"undefined"==typeof _speedMark?"-1":new Date-_speedMark,r4:h.pf||1},l;a:{try{var u=navigator,m=screen||{width:"",height:"",colorDepth:""},n=document.body,r=m.width+"x"+m.height,v=m.colorDepth+"-bit",C=(u.language||u.userLanguage).toLowerCase(),D=u.javaEnabled()?1:0,E=(new Date).getTimezoneOffset()/60,m="";n.addBehavior&&(n.addBehavior("#default#clientCaps"),m=n.connectionType);var n={fl:"",scr:r,scl:v,lg:C,jv:D,
tz:E,ct:m},k,i,f;if((l=u.plugins)&&(k=l.length))for(f=0;f<k;f++){if(i=l[f].description.match(/Shockwave Flash ([\d\.]+) \w*/))n.fl=i[1]}else f=(new ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version"),n.fl=f.replace(/^.*\s+(\d+)\,(\d+).*$/,"$1.$2")}catch(G){l={};break a}l=n}k={};if("undefined"!=typeof _taadHolders&&0<_taadHolders.length){i=0;f=_taadHolders;for(n=f.length;i<n;i++)k[f[i]]=k[f[i]]?k[f[i]]+1:1}i=[];for(var t in k)k.hasOwnProperty(t)&&i.push(t+"*"+k[t]);t={ext:"adid="+
i.join(":")};var g;k=[];for(g in o)(i=w(o[g].c_id),"afs"==g?f=(f=/ssid=([^&]*)/i.exec(s().hash))&&f[1]?f[1]:"":(f=s().param,f=f[o[g].id]?f[o[g].id]:""),f)?(k.push("ty="+o[g].key+";ck=0;id="+f),i=new Date,i.setTime(i.getTime()+2592E6),x(o[g].c_id,f,i.toGMTString())):i&&k.push("ty="+o[g].key+";ck=1;id="+i);g={pf:k.join("|")};g=[c,e,q,l,t,g,{random:+new Date}];for(c=g.length;b<c;b++)for(var j in g[b])g[b].hasOwnProperty(j)&&a.push(j+"="+(g[b][j]||""));d.params&&a.push(d.params);var A=Ta.src=("https:"==
document.location.protocol?"https://pingtas":"http://pingtcss")+".qq.com/pingd?"+a.join("&"),p=new Image;Ta[h.sid]=p;p.onload=p.onerror=p.onabort=function(){p=p.onload=p.onerror=p.onabort=null;Ta[h.sid]=true};p.src=A;if(1*!h.pf||h.hot.isValid){d=window.location;j=d.host+d.pathname;var F=d.pathname,B=function(){z("http://imgcache.qq.com/bossweb/ta/scripts/ping_hotclick_min.js",function(){window.hotclick&&(new hotclick(A)).watchClick()})};if(1*h.pf)RegExp(j).test(h.hot.url)&&B();else{j=h.sid;d="http://tcss.qq.com/heatmap/"+
j%100+"/";j+="";g=j.length;b=0;for(a="";b<g;){c=j.charCodeAt(b++)&255;if(b==g){a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(c>>2);a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt((c&3)<<4);a+="==";break}e=j.charCodeAt(b++);if(b==g){a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(c>>2);a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt((c&3)<<4|(e&240)>>4);a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt((e&
15)<<2);a+="=";break}q=j.charCodeAt(b++);a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(c>>2);a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt((c&3)<<4|(e&240)>>4);a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt((e&15)<<2|(q&192)>>6);a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(q&63)}z(d+a+".js?random="+ +new Date,function(){var a;if(window._Cnf&&(a=window._Cnf.url)){a=a.split("|");
for(var b=0;b<a.length;b++)if(a[b]==F){B();break}}})}}h.logo&&255!=h.logo&&(d=h.logo,j={9:"\u817e\u8baf\u5206\u6790",10:"\u7f51\u7ad9\u7edf\u8ba1",df:'<img src="http://tcss.qq.com/icon/toss_'+d+'.gif" border="0" />'},document.write(['<a href="http://ta.qq.com?ADTAG=FROUM.FOOTER.CLICK.ICON" title="\u817e\u8baf\u5206\u6790" target="_blank">',j[d]||j.df,"<a>"].join("")))}}var o={afs:{key:1,id:"ssid",c_id:"pgv_afsid",fr:"hash"},afc:{key:2,id:"__tacid",c_id:"pgv_afcid",fr:"param"},gdt:{key:11,id:"qz_gdt",
c_id:"pgv_gdtid",fr:"param"}};r.pgvSendClick=function(d,a){var b=Ta.src.replace(/ext=[^&]*/,function(){return"ext="+("evtid"==a?"ty=0;evtid=":"adid=")+d}).replace(/r2=([^&]*)/,function(a,b){return"r2=a"+b});(new Image(1,1)).src=b};r.Ta=r.Ta||{};Ta.pgv=v;!Ta.async&&v(Ta.hack?Ta.hack():"")})({sid:"",pf:"",hot:{url:"",isValid:!1}},this);
